//! Chiptune music playback, one track per `GameState`. Tracks are
//! generated by `tools/gen_chiptune_music.py` (see that script's
//! module docstring for the synthesis approach) and live under
//! `game/assets/audio/*.ogg`.
//!
//! Each state spawns its own track `OnEnter` and despawns it `OnExit`,
//! mirroring the existing per-state UI teardown convention (see
//! `board::BoardRoot`, `states::outage::OutageBanner`,
//! `states::results::ResultsRoot`). Because Bevy's state machine always
//! runs the old state's `OnExit` systems before the new state's
//! `OnEnter` systems for any transition, there is never a frame where
//! two tracks are both alive.

use crate::states::{GameState, LevelOutcome};
use bevy::prelude::*;

pub struct MusicPlugin;

impl Plugin for MusicPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(OnEnter(GameState::MainMenu), play_menu_theme)
            .add_systems(OnExit(GameState::MainMenu), stop_music)
            .add_systems(OnEnter(GameState::Playing), play_playing_theme)
            .add_systems(OnExit(GameState::Playing), stop_music)
            .add_systems(OnEnter(GameState::OutageActive), play_outage_theme)
            .add_systems(OnExit(GameState::OutageActive), stop_music)
            .add_systems(OnEnter(GameState::Results), play_results_jingle)
            .add_systems(OnExit(GameState::Results), stop_music);
    }
}

/// Marks the currently-playing music track's entity so `stop_music` can
/// find and despawn it on the way out of any state.
#[derive(Component)]
struct MusicTrack;

fn spawn_track(commands: &mut Commands, asset_server: &AssetServer, path: &str, looping: bool) {
    commands.spawn((
        MusicTrack,
        AudioBundle {
            source: asset_server.load(path.to_string()),
            settings: PlaybackSettings {
                mode: if looping {
                    bevy::audio::PlaybackMode::Loop
                } else {
                    bevy::audio::PlaybackMode::Despawn
                },
                ..default()
            },
        },
    ));
}

fn play_menu_theme(mut commands: Commands, asset_server: Res<AssetServer>) {
    spawn_track(&mut commands, &asset_server, "audio/menu_theme.ogg", true);
}

fn play_playing_theme(mut commands: Commands, asset_server: Res<AssetServer>) {
    spawn_track(
        &mut commands,
        &asset_server,
        "audio/playing_theme.ogg",
        true,
    );
}

fn play_outage_theme(mut commands: Commands, asset_server: Res<AssetServer>) {
    spawn_track(&mut commands, &asset_server, "audio/outage_theme.ogg", true);
}

/// Picks the win/fail jingle based on the same `LevelOutcome` resource
/// `results::show_results` reads to pick its banner and dialogue key.
fn play_results_jingle(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    outcome: Res<LevelOutcome>,
) {
    let path = if outcome.won {
        "audio/victory_jingle.ogg"
    } else {
        "audio/failure_jingle.ogg"
    };
    spawn_track(&mut commands, &asset_server, path, false);
}

fn stop_music(mut commands: Commands, tracks: Query<Entity, With<MusicTrack>>) {
    for entity in &tracks {
        commands.entity(entity).despawn();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every `.ogg` this module ever asks the asset server to load must
    /// actually exist under `game/assets/` — a typo here would otherwise
    /// only surface as silence at manual playtest, never a build error
    /// (`AssetServer::load` takes a path, not a compile-time checked
    /// handle).
    #[test]
    fn every_referenced_track_exists_on_disk() {
        for path in [
            "audio/menu_theme.ogg",
            "audio/playing_theme.ogg",
            "audio/outage_theme.ogg",
            "audio/victory_jingle.ogg",
            "audio/failure_jingle.ogg",
        ] {
            let on_disk = concat!(env!("CARGO_MANIFEST_DIR"), "/assets/").to_string() + path;
            assert!(
                std::path::Path::new(&on_disk).is_file(),
                "{on_disk} referenced by audio::MusicPlugin but missing on disk"
            );
        }
    }

    fn jingle_path_for(outcome: LevelOutcome) -> &'static str {
        if outcome.won {
            "audio/victory_jingle.ogg"
        } else {
            "audio/failure_jingle.ogg"
        }
    }

    #[test]
    fn results_jingle_path_matches_the_level_outcome() {
        assert_eq!(
            jingle_path_for(LevelOutcome { won: true }),
            "audio/victory_jingle.ogg"
        );
        assert_eq!(
            jingle_path_for(LevelOutcome { won: false }),
            "audio/failure_jingle.ogg"
        );
    }
}
